# Generated by Django 5.1.5 on 2025-02-11 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 6, 42, 34, 922467, tzinfo=datetime.timezone.utc)),
        ),
    ]
