# Generated by Django 5.1.5 on 2025-02-11 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 16, 37, 5, 479984, tzinfo=datetime.timezone.utc)),
        ),
    ]
