# Generated by Django 5.1.5 on 2025-02-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
